### ISSUE TITLE
DESIGN GUI TO MAKE IT PHYSICALLY ATTRACTIVE.

### ISSUE THREAD

**Issue by Pactopolis** [qWeX23/BlackJackSEM#19]

**Comment by qWeX23** [comment]
Delegate to @ProgrammerFrank  and @trm25  as needed

**Comment by qWeX23** [comment]
~~\* Change location and size of game state Label to make it not bad~~
~~\* update Stats Panel with appropriate info see #29~~

**Comment by qWeX23** [comment]
@ProgrammerFrank is there an ETA on this item?

**Comment by qWeX23** [comment]
Thank goodness this has been open for five years lol 😂

**Comment by Pactopolis** [comment]
I stumbled on it while working on a personal project using GitHub kanban boards lol very nostalgic

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
