### ISSUE TITLE
Dealer wins when tie 

### ISSUE THREAD

**Issue by qWeX23** [qWeX23/BlackJackSEM#23]
![image](https://cloud.githubusercontent.com/assets/11063838/11072411/506955ae-87ab-11e5-98a8-818e829cf70d.png)

@bat14 dosnt the Blackjack override the k+6+5 in this situation?

@cabreralcui @Silverterran @jlb151 if you find this issue please upload screenshot and command line output

thanks dudes

**Comment by bat14** [comment]
Yes a blackjack would win in that situation.

**Comment by bat14** [comment]
Sorry I couldn't make the meeting today guys. Had some family related
things I had to take care of today.

**Comment by qWeX23** [comment]
No worries,   just an update on this item.  I've added push in the playbj game, once I make it prioritize a bj I will make a new build to test

**Comment by qWeX23** [comment]
related to #25
