### ISSUE TITLE
Dealer does not bust/dealer still wins after bust

### ISSUE THREAD

**Issue by cabreralcui** [qWeX23/BlackJackSEM#3]
![image](https://cloud.githubusercontent.com/assets/9370440/10827231/ccf3b354-7e3b-11e5-9c4e-abaef99d2fb5.png)

Dealer busts after dealer's initial turn, but game does not end and dealer still wins.

**Comment by cabreralcui** [comment]
For this specific game, the dealer and the player's initial hands were 15 and 12, respectively. After the dealer gave itself a card, it raised its hand total to 25. The dealer should have busted then. 

However, the game still gives an option for the player to hit. I chose to hit and got a score of 17 versus the dealer's 25. I should have won, but the game still lets the dealer win anyway.

**Comment by qWeX23** [comment]
This will be fixed in the new version

**Comment by qWeX23** [comment]
![image](https://cloud.githubusercontent.com/assets/11063838/10870637/3f05607c-8095-11e5-800d-d05eff910c80.png)

lol i didnt do it hahaha xd jk i did

**Comment by Pactopolis** [comment]
Okay. Heads up though, the dealer shouldn't know his second card until
after the player has stayed.
