### ISSUE TITLE
Player Bust when 19?

### ISSUE THREAD

**Issue by qWeX23** [qWeX23/BlackJackSEM#33]
![image](https://cloud.githubusercontent.com/assets/11063838/11171598/d0464d7e-8bb9-11e5-9b35-f3e9e79892b4.png)

i dont understand would anyone mind trouble shooting this if they get a chance?

**Comment by PaddyLevitt** [comment]
I don't know about the player bust part but I fixed the dealer not hitting
with 16 or less. I'll look at it here in a few.

**Comment by qWeX23** [comment]
Dealer will not even try if player is already  bust. I appreciate you
looking into that for me.  I have the tutorial technically working but it
won't switch between tutorials and game

**Comment by PaddyLevitt** [comment]
Basically I made the dealer hit below 16 and stay on 17, if the player did
not bust. It doesn't matter if the dealer has a better hand when the player
stands, he still has to hit on 16 or lower. Maybe that fixed some other
issue logs, I don't know. Finishing up ethical hacking lab, then i'll look
at the player busts on 19 thing it seems like that second ace is being
counted as 11?

**Comment by PaddyLevitt** [comment]
Got it!

The following combinations yield as follows:

10 + A = 21
3 + 6 + A + 2 + 2 + 2 + 2 + A = 19
3 + 6 + A + 2 + 2 + 2 + 2 + A + A = 20
3 + 6 + A + 2 + 2 + 2 + 2 + A + A + A= 21
3 + 6 + A = 20
3 + 6 + A + A = 21

Going to commit changes to calculateHandPower method in Hand class and sign
off issue #33.

**Comment by qWeX23** [comment]
Sweet
